### ISSUE TITLE
Periods and the space of holomorphic forms

### ISSUE THREAD

**Issue by videlec** [flatsurf/article#4]
Given a translation structure $(X, \omega)$ we want to be able to solve the following Dirichlet like problem: given a cohomology class $\eta \in H^1(X; R)$ compute the unique holomorphic one-form $\zeta$ such that $[\Re (\zeta)] = \eta$ in $H^1(X; R)$.

**Comment by saraedum** [comment]
Is this essentially https://github.com/flatsurf/sage-flatsurf/issues/181?

**Comment by saraedum** [comment]
Not sure why this is in the `article` repo. Feel free to reopen/move.
